### ISSUE TITLE
Fix IP Address Information from user when access

### ISSUE THREAD

**Issue by trongvominh** [huongdanjavacom/mvnForumJ#17]
![image](https://user-images.githubusercontent.com/7220354/127796425-7bc03558-1156-4118-874c-9daa536aea27.png)

**Comment by khanhnguyenj** [comment]
This issue happened when deploying Apache Tomcat behind an Apache 2 proxy.

Fixed by adding a valve in tomcat/conf/server.xml: 
`<Valve className="org.apache.catalina.valves.RemoteIpValve" remoteIpHeader="x-forwarded-for" />`
